services:
  producer:
    build: .
    command: wait-for-it -t 0 rabbit:5672 -- python -m pubsub.producer
    depends_on:
      - rabbit
    environment:
      - RABBITMQ_URL=amqp://guest:guest@rabbit:5672/%2F
    volumes:
      - .:/app

  consumer1:
    build: .
    command: wait-for-it -t 0 rabbit:5672 -- python -m pubsub.consumer
    depends_on:
      - rabbit
    environment:
      - RABBITMQ_URL=amqp://guest:guest@rabbit:5672/%2F
      - QUEUE=consumer1.logs
    volumes:
      - .:/app

  consumer2:
    build: .
    command: wait-for-it -t 0 rabbit:5672 -- python -m pubsub.consumer
    depends_on:
      - rabbit
    environment:
      - RABBITMQ_URL=amqp://guest:guest@rabbit:5672/%2F
      - QUEUE=consumer2.logs
    volumes:
      - .:/app

  rabbit:
    image: rabbitmq:3.9.10-management
    volumes:
      - .data/rabbitmq:/var/lib/rabbitmq/
    ports:
      - 5672:5672
      - 15672:15672
